In [1]:
import torch

In [2]:
torch.rand(2, 3)

tensor([[0.2193, 0.8735, 0.8418],
        [0.2732, 0.2069, 0.4897]])

In [5]:
x = torch.ones(2, 3)

In [6]:
x.fill_(5)

tensor([[5., 5., 5.],
        [5., 5., 5.]])

From numpy

In [7]:
import numpy as np

In [8]:
npy = np.random.rand(2, 3)

In [9]:
torch.from_numpy(npy)

tensor([[0.2814, 0.6450, 0.2557],
        [0.8307, 0.0714, 0.6891]], dtype=torch.float64)

Tensor Operations

In [10]:
x = torch.randn(2, 3)

In [14]:
x

tensor([[-1.8085,  2.2417, -0.5535],
        [ 0.1743,  1.8445, -0.8832]])

In [13]:
torch.add(x, x)

tensor([[-3.6170,  4.4834, -1.1070],
        [ 0.3485,  3.6890, -1.7665]])

In [15]:
x + x

tensor([[-3.6170,  4.4834, -1.1070],
        [ 0.3485,  3.6890, -1.7665]])

In [16]:
x = torch.arange(6)

In [17]:
x

tensor([0, 1, 2, 3, 4, 5])

In [19]:
x = x.view(2, 3)

In [20]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [21]:
torch.sum(x, dim = 0)

tensor([3, 5, 7])

In [22]:
torch.sum(x, dim = 1)

tensor([ 3, 12])

In [28]:
torch.transpose(x, 0, 1)

tensor([[0, 3],
        [1, 4],
        [2, 5]])

Index, Slicing, Joining

In [29]:
x = torch.arange(6).view(2, 3)

In [32]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [34]:
x[:1, :2]

tensor([[0, 1]])

In [38]:
x[1, 2]

tensor(5)

Index

In [40]:
row_indicies = torch.arange(2).long()
col_indicies = torch.LongTensor([0, 1])

In [41]:
row_indicies

tensor([0, 1])

In [42]:
col_indicies

tensor([0, 1])

In [43]:
x[row_indicies, col_indicies]

tensor([0, 4])

Concatenating tensors

In [44]:
x = torch.arange(6).view(2, 3)

In [46]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [47]:
torch.cat([x, x], dim = 0)

tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])

In [48]:
torch.cat([x, x], dim = 1)

tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])

In [49]:
torch.stack([x, x])

tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])

Linear algebra on tensors: multiplication

In [71]:
x1 = torch.arange(6, dtype=torch.float32).view(2, 3)

In [72]:
x1

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [73]:
x1.type()

'torch.FloatTensor'

In [63]:
x2 = torch.ones(3, 2)

In [64]:
x2

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [65]:
x2[:, 1] += 1

In [69]:
x2.type()

'torch.FloatTensor'

In [66]:
x2

tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])

In [74]:
torch.mm(x1, x2)

tensor([[ 3.,  6.],
        [12., 24.]])

Tensors and Computational Graphs

In [75]:
x = torch.ones(2, 2, requires_grad=True)

In [76]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [77]:
x.grad is None

True

In [91]:
y = (x + 2) * (x + 5) + 3

In [92]:
y

tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)

In [93]:
x.grad is None

False

In [94]:
z = y.mean()
print(z)
z.backward()
print(x.grad is None)

tensor(21., grad_fn=<MeanBackward1>)
False


When you create a tensor with requires_grad=True, you are requiring PyTorch to manage bookkeeping information that computes gradients. First, PyTorch will keep track of the values of the forward pass. Then, at the end of the computations, a single scalar is used to compute a backward pass. The backward pass is initiated by using the backward() method on a tensor resulting from the evaluation of a loss function. The backward pass computes a gradient value for a tensor object that participated in the forward pass.

In general, the gradient is a value that represents the slope of a function output with respect to the function input. In the computational graph setting, gradients exist for each parameter in the model and can be thought of as the parameter's contribution to the error signal. In PyTorch, you can access the gradients for the nodes in the computational graph by using the .grad member variable. Optimizers use the .grad variable to update the values of the parameters.

### **CUDA Tensors** 

#### Creating CUDA tensors

In [95]:
torch.cuda.is_available()

False

In [96]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [97]:
print(device)

cpu


In [98]:
x = torch.rand(3, 3).to(device)

In [99]:
x.type()

'torch.FloatTensor'